### ISSUE TITLE
Status issue when running on App Engine module

### ISSUE THREAD

**Issue by dalippa** [GoogleCloudPlatform/appengine-pipelines#12]
I am running Mapreduce on a "module" and when I generate a pipeline status URL, I always get this kind of error:

/mapreduce/pipeline/status?root=dc2fb2204e404116ac2a6f2dbff3e8f2

Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~realmassive-mr/tasks:mr.381800281691572294/distlib/pipeline/status_ui.py", line 73, in get
    self.redirect(users.create_login_url(self.request.url))
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/users.py", line 258, in create_login_url
    raise NotAllowedError
NotAllowedError

However, when I go to an individual task's status URL, everything works fine:

/mapreduce/status
/mapreduce/detail?mapreduce_id=1575755193601C7155E4D

**Comment by dalippa** [comment]
I will also note that this works just fine when deployed onto a "front end" instance.

**Comment by tkaitchuck** [comment]
Yes, that is unfortunate. Secure-by-default is running afoul of an easy demo.
The solution is to go to http://localhost:8080/_ah/login  
and check the box that says administrator and press login. That will enable viewing the status page. 
I'll add a note to that effect in the wiki.
